
const activities = [
    {
    id: 1,
    title: "The Women's Network President",
    skills: "Leadership, event planning, communication, Mailchimp",
    date: "2013 - Present",
    description: "Manages organization of 280 members. Grew membership by 29% in the 2024-2025 school year. Manages all external affairs, including the chapter’s registration status with the Georgia Tech. Oversees all chapter-level meetings and events. Coordinates and moderates speakers events. Sends weekly Mailchimp emails. Plans and leads weekly Executive Board meetings. Attends biweekly TWN President Meetings. Attends TWN National events. Ensures that all meetings/events are high-quality, all marketing is consistent, and the chapter’s values meet the organization’s expectations and standards. Interviews, selects, and onboards new Executive Board leaders, and helps the chapter transition to the new team",
    icon: "",
  },
  {
    id: 1,
    title: "Tech Lead in Georgia Tech's IOS Club",
    skills: "SwiftUI, Firebase, Leadership",
    date: "Aug 2024 - Present",
    description: "Contributed to Loop: a watch os app as a member, Keepsake: an augmented reality scrapbooking app as a Senior Developer and Yes Chef: a competitive cooking social media app as Tech Lead.",
    icon: "",
  },
  {
    id: 1,
    title: "Tech Lead in Georgia Tech's Android Studio Club",
    skills: "Kotlin, Firebase, Java",
    date: "Aug 2024 - Present",
    description: "Contributed to GT's carpooling app and UNIty: a roommate finder app as Tech Lead.",
    icon: "",
  },
  {
    id: 1,
    title: "Video Game Development Club",
    skills: "C#, Unity, Blender",
    date: "Jan 2025 - Present",
    description: "Member of GT's VG dev organization. Currently am working on a cute cafe video game.",
    icon: "",
  },
  {
    id: 1,
    title: "Piano",
    skills: "Piano, Music Theory",
    date: "2013 - Present",
    description: "Passed 11 out of the 11 MN state level exams with high distinctions. 6 time state finalist in Minnesota Music Teachers Association piano competition",
    icon: "fa-solid fa-music",
  },
  {
    id: 1,
    title: "National Speech and Debate Organization",
    skills: "Speaking, Leadership, Quick Thinking, Economics knowledge, Politics knowledge",
    date: "2017-2023",
    description: "Captain of my high school's speech team. I competed in Oratory (persuasive speech category): 65th at national NCFL tournament, 7th at MN State Nat Quals. Competes in Extemp Speaking (Category in which student is given 30 minutes to write and memorize a 7 minute speech about any international political topic): 95th at 2021 National NIETOC tournament. Competed in Storytelling in 7th grade and Extemp Speaking in 8th grade at my middle school speech team and earned first place both years.",
    icon: "fa-solid fa-comment",
  },
  {
    id: 1,
    title: "Dance: Bharathanatyam, Hiphop, Bollywood",
    skills: "Dance",
    date: "2010-Present",
    description: "I have been learning Bharathanatyam, a classical Indian dance, for 10 years. Performed at 70+ stages and competitions. Helped organize my Bharathanatyam teacher's annual dance program. I choreograph and perform Bollywood dances and have done so since I was 5. Performed my own choreography in front of my entire school in 8th grade, 12th grade and for festivals at my College. I'm also a part of ATL Satrangi: A National Competing College Dance Team",
    icon: "",
  },
  {
    id: 1,
    title: "National Center for Women and Information Technology Member",
    skills: "Computer Science",
    date: "2022 - Present",
    description: "I was honored to be the 2023 State Winner and 2022 State Honorable Mention for the Aspirations in Computing Scholarship Program, which recognizes young women for their achievements and aspirations in technology and computing. Through the Minnesota Aspirations in Computing (MNAiC) shadowing program, I had the unique opportunity to shadow the CIO of Pohlad Companies, where I gained firsthand insight into how technology supports and drives success across different areas of a business. Additionally, I participated in MNAiC’s Mentor Mash program, where I was mentored by a professional computer scientist. She provided valuable guidance and shared resources, including online courses in web development and articles on artificial intelligence — which helped deepen my understanding of computer science and its real-world applications.",
    icon: "fa-solid fa-computer",
  },
  {
    id: 1,
    title: "Bookstagram and Book Blog",
    skills: "Writing, Photography",
    date: "2019 - Present",
    description: "I'm the creator behind @bookconfessionssecrets, an Instagram account dedicated to all things books. I share aesthetic book photography and create relatable, engaging reels to connect with fellow readers. The account has grown to over 8,200 followers, and several of my reels have gone viral. One reel reached 14 million views. I've collaborated with numerous authors on book tours and promotional content, helping bring attention to new and upcoming titles. In addition, I run a book blog at bookconfessionssecrets.wordpress.com, where I post reviews of the books I read. The blog receives over 2,000 monthly views, and several authors have reached out directly requesting reviews for their books.",
    icon: "fa-solid fa-book",
  },
  {
    id: 1,
    title: "Pass Tutoring",
    skills: "Math, Science, Communication, Leadership",
    date: "Sept 2021 - June 2023",
    description: "Increased participation and member numbers by 30% between 2021 to 2022. 25 hours of service.",
    icon: "fa-solid fa-book",
  },
  {
    id: 2,
    title: "Trace Tutoring",
    skills: "Math, Science, Communication, Leadership",
    date: "Sept 2022 - June 2023",
    description: "As President of my high school’s tutoring club, I led a team of over 100 student tutors and helped organize academic support across multiple subjects. I collaborated with school administration to introduce a graduation cord incentive program, recognizing students who dedicated significant time to tutoring their peers. Personally, I have contributed 30+ hours of volunteer tutoring, supporting students both academically and through mentorship.",
    icon: "fa-solid fa-book",
  },
    {
      id: 4,
      title: "USA Computing Olympics",
      skills: "Java, Algorithms, Leadership, Communication, Problem Solving",
      date: "Sept 2022 - June 2023",
      description: "Founded the USA Computing Olympics club at my high school. The club is for bringing members together for group practice towards developing algorithms and creating Java programs for competing nationwide in USA Computing Olympics. ",
      icon: "fa-solid fa-computer",
    },
    {
      id: 4,
      title: "Girls who Code Member",
      skills: "HTML, CSS, Javascript, Cybersecurity, Cryptography",
      date: "2022 - Present",
      description: "Earned 5 certifications at Girls Who Code coding program: HTML and CSS, Javascript, Web design for Social Good, Intro to Cybersecurity and Intro to Cryptography. Actively apart of the club and have attended events such as Girls Who Code career fair and the Girls Who Code x Logitech event!",
      icon: "fa-solid fa-computer",
    },
    {
      id: 4,
      title: "Ink and Fable Book Club founder",
      skills: "",
      date: "September 2022 - June 2023",
      description: "Founder and captain of my high school's book club. Organized school wide events such as Book Trivia night and the Book Awards",
      icon: "fa-solid fa-book",
    },
  ];
  
  export default activities;
