const projects = [
  {
    id: 1,
    title: "Senior Developer for Keepsake",
    skills: "Swift, WatchOS, Multipeer Connectivity Framework, AR Framework, ChatGPT API",
    date: "January 2025 - April 2025",
    description: "Keepsake encourages motivates users to journal by incorporating 3D elements with the AR Scrapbooks, interactive journal elements like stickers, an AI chatbot and voice journal entries via watch component. Users can browse through Scrapbook templates shared by others!",
    icon: "fa-solid fa-book",
  },
  {
    id: 1,
    title: "Storefront Visibility - Hackathon 2nd Place Winner",
    skills: "Python",
    date: "February 2025",
    description: "Developed an algorithm using Google Maps API, OpenStreetMap, and Detectron2 to measure storefront visibility within a 75-meter radius.",
    icon: "fa-solid fa-street-view",
  },
  {
    id: 1,
    title: "Vertically Integrated Projects Research Program - ACT Driving Simulatorr",
    skills: "Python",
    date: "January 2025 - May 2025",
    description: "Detected driver drowsiness using OpenCV and by calculating Eye Aspect Ratio.",
    icon: "fa-solid fa-car",
  },
  {
    id: 1,
    title: "Tech Lead for UNIty",
    skills: "Kotlin, Java",
    date: "January 2025 - Present",
    description: "UNIty helps Georgia Tech students find roommates on campus depending on their rooming preferences (sleeping habits, personality types, housing location, room temperature preferences, etc).",
    icon: "fa-solid fa-home",
  },
  {
    id: 1,
    title: "Team Project - SpotiFye",
    skills: "Django, Python, HTML & CSS, JavaScript, Github",
    date: "October 2024 - December 2024",
    description: "Lets users see their short, medium and long term spotify wrapped data and play mini games based on their listening history. Built functionality using Hugging Face llm to infer the listener's personality from their song choices. Developed mini games by blurring the album's cover and having the user guess songs from their top 50 listened songs.",
    icon: "fa-solid fa-music",
  },
  {
    id: 1,
    title: "Team Project - Loop",
    skills: "SwiftUI, WatchOS, HealthKit",
    date: "September 2024 - November 2024",
    description: "Team project with IOS Club. This app lets users start an activity on their watch, record their data and compete in challenges against other users.",
    icon: "fa-solid fa-running",
  },
  {
    id: 2,
    title: "Team Project - GT Carpooling",
    skills: "Kotlin, Java, Android Studio IDE, Firebase",
    date: "September 2024 - November 2024",
    description: "Team project with GITMAD Club. This app lets Georgia Tech students request and offer carpool rides.",
    icon: "fa-solid fa-car",
  },
  {
    id: 2,
    title: "Team Project - ATL Food Finder",
    skills: "Django, Python, Pycharm IDE, Github, CSS, HTML, JavaScript, Google Maps API",
    date: "September 2024 - November 2024",
    description: "This website lets users browse restaurants and fast food chains across Atlanta. Users are able to log in, save their favorite restaurants and filter search on the map to find food by cuisine type, distance and restaurant rating.",
    icon: "fa-solid fa-utensils",
  },
    {
      id: 3,
      title: "Personal Project - Chess Timer",
      skills: "SwiftUI",
      date: "Aug 2nd 2024",
      description: "Users can choose the amount of time each players gets overall. When they tap their timer, their lock ends and the opponent's clock starts.",
      icon: "fa-solid fa-chess",
    },
    {
      id: 4,
      title: "Personal Project - Book Annotations App",
      skills: "SwiftUI, Firebase",
      date: "May-June 2024",
      description: "Users are able to digitally annotate books by pointing their camera over the passage they want to annotate. The app will scan the text and the user will be able to add their annotations/thoughts for the text. Using Firebase, the app stores data for each annotation categorized by user and by the book they annotated.",
      icon: "fa-solid fa-book",
    },
    {
      id: 4,
      title: "Personal Project - TA Office Hours Waitlist",
      skills: "JavaScript, Firebase, HTML, CSS",
      date: "July 2024",
      description: "Created functionality for students taking Georgia Tech's Discrete Math course to leave and enter the waitlist based on their anonymous authentication. Developed a feature where teachers can sign in to view the list of students and remove them if necessary.",
      icon: "fa-solid fa-book",
    },
    {
      id: 4,
      title: "Team Project - Epic Intentions Consulting Organization Website",
      skills: "React JS, Tailwind CSS, Figma, Github",
      date: "May-Aug 2024",
      description: "Designed and developed desktop & mobile responsive website pages.",
      icon: "fa-solid fa-book",
    },
  ];
  
  export default projects;
  